VERSION="2.0.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
# Federation service provided by StellarID.io
FEDERATION_SERVER="https://stellarid.io/federation/"
HORIZON_URL="https://horizon.stellar.org"
ACCOUNTS=[
"GA2RA7E7QWBJUV3EEVJZYKOURVAAYIK2X33NQLY6GMEBHQSD3NDB7NP7","GA6NNVG2RV2VUGGELX6LRA4HVNB2R33F7ZZ2CWNGD52VJ3HCBTAYKUQP",
"GAAZZN24QGHG63MOAIC2QQ5XDKI3T6R2RGEZ4L6T4MA3UF6YIH73K7LB","GANKNLWTIW2S6C4OM4CSUYHXV235UUF5VYPQE2RBWOKJ6IMMU4IQVFR5",
"GARFVYJUGZNPNT24RNBC5R4VZU3Y2ZEBEUMIO5R6VHHCPWQ3AP43HQI3","GAWCNJ43AGVERDLCMF5NVFQMPJ75XYKC3GS3KZ3KP63QAS2MJOE32KKW",
"GAXO5FNPRCT4M54VPYIC6T2RMLQKPR246SN2L4QYD5L2ETLKXRD3LWUE","GB4HCB2EQML2KRMJCWECWS6XDCYWAFAKX5FUDQNXSWDIWDZZGBFICNKR",
"GBKHAJYDVIWLKKV7RJFQZGPXXPOMENMPKSUCOOUO5QBPOKXAN5SRJFNP","GCF2T2JXLANAS3FLH2IANQOUDVQ7A62AJPCJZIMD5Y6IMIVFSJHKCNA3",
"GB7JNFD7BMXFVLMQR6KG7ZABEOALQ5JGQ4KE2Z3OGF3QXGODCALTKF2T","GBDVCDD32QQX7UTMKUO2EMF2ZUO63WID6TE52TOTVMSGP5SRFFHHAJ6N",
"GBEPPQIMNGPWIEQNSU4GZZNPTNYDXILJJDSBE6YIYIMUADTC66Z45ILK","GBFSLMUD5WAMFD44J3TTVJBLK3BOWD3JOREFCMQQOBXPARC23TSGQEAZ",
"GBIDGDSVQXAHGZNOETS7ADUMWCDSQJU4R53EZRK6ONP3BA42UJL5PAHR","GBIY73VZ674EHEQJ3DSVEWHWIYXGXPXTYHPHKMKXVVTZF2NVGTN5QVH6",
"GBYOAJ5DBJMFSHMJQDMPHBSSJYIN6YIV5QCK4VY5DFRJEY4K5IRGNA57","GC2EODUKTSOIWSJDL5ZM7FFFWEA3BNHF6II4KZYZPJIBQ7KL2VOOMABQ",
"GCK3E7OOLG4JLKOSGJLEQKSWMNH6SBNXSYESMYPRH5M77DJ7AXMJENPF","GD7VVTAAAJ4ORW2QC2CQIMPU5S3SEI3HBTKZ7B4DN3JGJSHWZQN6VLW5",
"GAAJRBV3KR3ZJCKVV3R7SB3RMBUGTCUS66QUZICSQJMJC2G3OAT7L7YQ","GAWTLCOEJQBOHB33OZWVP6LNIOBU2F6POFR3Y5IVRJZW7PV32KGWE4OH",
"GAY762QGZAGF7HEPDKCOLON3X3ISH733FJQTGSDHK47BUP75X3QNF4ZU","GBVGSELMRQXPMKPR4FUC6VWFYOGVRCJ7B2UUP7D2MIMW6H34CJSWFAYO",
"GC6SLUVAXVUGPCMOPJZG4XIDWX4UFFEZ3KUH7HZ2EFENVSA46KAJQKRJ","GC7HKFCM4KSAGWVCSLVLB7U4BUYMMNNXJVXENOO2FCTUKPZ3ZLM7JNI2",
"GCC7BSGQUGCD6IZXSWYP5GC73B62MTVQ4FBYTKDJAR4AVCSZAPEQ4FMK","GCKXURGL26UV6RXESH2BJXFLIJHJDZK7GCFEMW4IIQ7KZEG7AIJQPKL2",
"GCLJ67U6KQ7DAX3DIHMURXSFGPQ45PAPTEU6LVXDBSDXWRDTZJCUEC5F","GDXMWUUOAK42FJ4OCMSIO627FPCRKVYA7YZXD2ONF63ZDWZAWE25DDMS"]
